# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_cards',
                'doc_host': 'https://rleyvasal.github.io',
                'git_url': 'https://github.com/rleyvasal/nbdev_cards',
                'lib_path': 'nbdev_cards'},
  'syms': { 'nbdev_cards.core': { 'nbdev_cards.core.Card': ('card.html#card', 'nbdev_cards/core.py'),
                                  'nbdev_cards.core.Card.__init__': ('card.html#__init__', 'nbdev_cards/core.py'),
                                  'nbdev_cards.core.Card.__str__': ('card.html#__str__', 'nbdev_cards/core.py'),
                                  'nbdev_cards.core.foo': ('card.html#foo', 'nbdev_cards/core.py')}}}